import type { Account, AgentChat, Campaign, Profile, Schedule, ToolStat } from './types'

export const tools = ['update_bids', 'get_campaign_metrics', 'create_campaign', 'harvest_keywords', 'analyze_acos', 'budget_report', 'pause_entities', 'search_terms']
export const optActions = ['Bid Optimization', 'Budget Optimization', 'Placement Optimization', 'Budget Dayparting', 'Goal-Based Optimization']
export const launchActions = ['Keyword Harvesting', 'Campaign Generation', 'Cyber Minigun']
export const actionCn: Record<string, string> = { 'Bid Optimization': '竞价优化', 'Budget Optimization': '预算优化', 'Placement Optimization': '版位优化', 'Budget Dayparting': '预算分时', 'Goal-Based Optimization': '目标优化', 'Keyword Harvesting': '关键词收割', 'Campaign Generation': '广告活动生成', 'Cyber Minigun': 'Cyber Minigun' }

const split = (i: number) => ({ sp: 40 + i * 3, sb: 18 + i * 2, sd: 9 + i })
export const accounts: Account[] = Array.from({ length: 14 }, (_, i) => ({ id: `acc-${i + 1}`, name: ['Anotion Labs', 'Nimbus Commerce', 'Peak Goods', 'Northstar Retail'][i % 4] + (i > 3 ? ` ${i + 1}` : ''), plan: ['Enterprise', 'Growth', 'Starter'][i % 3], status: (['Healthy', 'Moderate', 'At Risk', 'Churned'][i % 4]) as Account['status'], joined: `202${i % 4}-0${(i % 8) + 1}-12`, lastActive: `${i + 1} days ago`, renewal: `2026-${String((i % 9) + 1).padStart(2, '0')}-2${i % 8}`, adsConn: [i % 3 + 1, 3], profConn: [i % 2 + 1, 2], subConn: [2 + (i % 3), 4], ams: [i % 4, 4], sp: [i % 3, 4], spend: 18000 + i * 2370, spendSplit: split(i), chats: 120 + i * 13, optEvents: 40 + i * 9, schedRuns: 80 + i * 11, launched: { sp: i % 4, sb: (i + 1) % 3, sd: i % 2 } }))
export const profiles: Profile[] = accounts.flatMap((a, ai) => Array.from({ length: 2 }, (_, pi) => ({ id: `${a.id}-p${pi + 1}`, name: `${['US', 'DE', 'UK', 'JP'][pi + ai % 4]}: ${a.name.split(' ')[0]}`, marketplace: ['US', 'DE', 'UK', 'JP'][pi + ai % 4], entity: pi ? 'Vendor' : 'Seller', account: a.name, accountId: a.id, plan: a.plan, joined: a.joined, lastActive: a.lastActive, renewal: a.renewal, adsApi: true, amsApi: ai % 4 !== 0, spApi: ai % 3 !== 0, spend: 7200 + ai * 530 + pi * 800, sales: 26400 + ai * 1500 + pi * 900, acos: 22 + (ai % 8), tacos: 8 + (pi * 2), orders: 120 + ai * 8, impr: 120000 + ai * 7000, clicks: 9200 + ai * 400, cpc: 0.78 + pi * 0.08, cvr: 8.2 + pi, schedRuns: 28 + ai * 2, activeSched: 3 + pi, optEvents: 46 + ai * 3, bids: 24 + ai, budgets: 16 + pi, placements: 9 + ai, chats: 14 + ai, launched: { sp: 2 + pi, sb: 1, sd: 1 }, targeting: { sp: 3, sb: 1, sd: 1 } })))
export const campaigns: Campaign[] = profiles.flatMap((p, pi) => Array.from({ length: 5 }, (_, i) => ({ id: `${p.id}-c${i + 1}`, profileId: p.id, name: `${p.name.split(': ')[1]} ${['Core', 'Brand', 'Defense', 'Generic', 'Harvest'][i]} ${i + 1}`, adType: ['SP', 'SB', 'SD'][i % 3], managedBy: [optActions[i % optActions.length]], affectedBy: [optActions[(i + 1) % optActions.length]], launchedBy: launchActions[i % launchActions.length], spend: 850 + pi * 60 + i * 120, sales: 3200 + pi * 200 + i * 300, acos: 18 + i * 2, orders: 24 + i * 3, impr: 28000 + i * 2300, clicks: 2100 + i * 190, cpc: 0.72 + i * 0.04, cvr: 7.2 + i * 0.5, optEvents: 3 + i, bids: 2 + i, budgets: 1 + (i % 3), placements: i % 2 })))
export const schedules: Schedule[] = profiles.flatMap((p, pi) => [...optActions.slice(0, 3), ...launchActions.slice(0, 2)].map((action, i) => ({ id: `SCH-${String(pi * 10 + i + 1001)}`, profileId: p.id, action, adType: ['SP', 'SB', 'SD'][i % 3], name: `${action} · ${p.name}`, status: i % 4 === 0 ? 'Paused' : 'Active', user: ['admin', 'sarah', 'mike'][i % 3], alarm: i % 5 === 0, created: `2026-0${(i % 8) + 1}-0${(i % 8) + 1}`, lastResult: i % 5 === 0 ? 'Failed' : i % 3 === 0 ? 'Partial' : 'Success', runs: 12 + i, managed: 18 + i, unmanaged: 4 + (i % 3), bidsOpt: 14 + i, campLaunched: 3 + i, adGroups: 5 + i, targeting: 8 + i })))
export const toolStats: ToolStat[] = tools.map((tool, i) => ({ tool, profilesUsing: i === 7 ? 0 : 8 + i, calls: i === 7 ? 0 : 120 + i * 23, lastCalled: i === 7 ? null : `${i + 1} days ago`, success: i === 7 ? null : 92 - i * 2, errors: i === 7 ? 0 : i + 1 }))
export const agentChats: AgentChat[] = Array.from({ length: 12 }, (_, i) => ({ name: `Chat ${i + 1} · ${profiles[i % profiles.length].name}`, date: `2026-08-${String(31 - i).padStart(2, '0')}`, sub: `operator_${i % 4 + 1}`, first: ['How are my bids performing?', 'Show campaign metrics', 'Harvest keywords for SP'][i % 3], summary: 'Agent reviewed recent performance and returned actionable campaign context.' }))
