/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/sign-in'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/': RouteRecordInfo<
      '/marketing/',
      '/marketing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/prompt-editor': RouteRecordInfo<
      '/marketing/prompt-editor',
      '/marketing/prompt-editor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/wecom-chat-history': RouteRecordInfo<
      '/marketing/wecom-chat-history',
      '/marketing/wecom-chat-history',
      Record<never, never>,
      Record<never, never>,
      | '/marketing/wecom-chat-history/group/[roomid]'
      | '/marketing/wecom-chat-history/private/[thread_id]'
    >,
    '/marketing/wecom-chat-history/group/[roomid]': RouteRecordInfo<
      '/marketing/wecom-chat-history/group/[roomid]',
      '/marketing/wecom-chat-history/group/:roomid',
      { roomid: ParamValue<true> },
      { roomid: ParamValue<false> },
      | never
    >,
    '/marketing/wecom-chat-history/private/[thread_id]': RouteRecordInfo<
      '/marketing/wecom-chat-history/private/[thread_id]',
      '/marketing/wecom-chat-history/private/:thread_id',
      { thread_id: ParamValue<true> },
      { thread_id: ParamValue<false> },
      | never
    >,
    '/marketing/wecom-customers': RouteRecordInfo<
      '/marketing/wecom-customers',
      '/marketing/wecom-customers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/marketing/wecom-leads': RouteRecordInfo<
      '/marketing/wecom-leads',
      '/marketing/wecom-leads',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/raas/': RouteRecordInfo<
      '/raas/',
      '/raas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/raas/dashboard/': RouteRecordInfo<
      '/raas/dashboard/',
      '/raas/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/display': RouteRecordInfo<
      '/settings/display',
      '/settings/display',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/sign-in'
      views:
        | 'default'
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
    }
    'src/pages/marketing/index.vue': {
      routes:
        | '/marketing/'
      views:
        | never
    }
    'src/pages/marketing/prompt-editor.vue': {
      routes:
        | '/marketing/prompt-editor'
      views:
        | never
    }
    'src/pages/marketing/wecom-chat-history.vue': {
      routes:
        | '/marketing/wecom-chat-history'
        | '/marketing/wecom-chat-history/group/[roomid]'
        | '/marketing/wecom-chat-history/private/[thread_id]'
      views:
        | 'default'
    }
    'src/pages/marketing/wecom-chat-history/group/[roomid].vue': {
      routes:
        | '/marketing/wecom-chat-history/group/[roomid]'
      views:
        | never
    }
    'src/pages/marketing/wecom-chat-history/private/[thread_id].vue': {
      routes:
        | '/marketing/wecom-chat-history/private/[thread_id]'
      views:
        | never
    }
    'src/pages/marketing/wecom-customers.vue': {
      routes:
        | '/marketing/wecom-customers'
      views:
        | never
    }
    'src/pages/marketing/wecom-leads.vue': {
      routes:
        | '/marketing/wecom-leads'
      views:
        | never
    }
    'src/pages/raas/index.vue': {
      routes:
        | '/raas/'
      views:
        | never
    }
    'src/pages/raas/dashboard/index.vue': {
      routes:
        | '/raas/dashboard/'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
    }
    'src/pages/settings/display.vue': {
      routes:
        | '/settings/display'
      views:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
